import type { NextPage } from "next";
import Head from "next/head";
import { prisma } from "../db/client";

const Home: NextPage = (props: any) => {
  return (
    <div className="text-2xl">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <code>{props.questions}</code>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const questions = await prisma.pollQuestion.findMany();

  return {
    props: {
      questions: JSON.stringify(questions),
    },
  };
};
